### ISSUE TITLE
does not work with all of floodwarning

### ISSUE THREAD

**Issue by Downanddirty4568** [Morris1927/RoR2-projects#1]
i was playing a run of huntress and i had two ai helpers with me, from the floodwarning mod, and a whole bunch of missile drones, i saved the game, when i reloaded, i did not have my missile drones or my Ai teammates

**Comment by Morris1927** [comment]
The next version of SavedGames will save the missile drones, unfortunately I'm not sure if the flood warning AI teammates will carry over (though they should, but they might not have AI)
