### ISSUE TITLE
RoR2 crashes when I start a game

### ISSUE THREAD

**Issue by Kelema** [Morris1927/RoR2-projects#4]
Whenever I try to start a game with this mod, the game freezes. This is what the console looks like.
![Console](https://user-images.githubusercontent.com/21977473/57478934-17e03d80-7251-11e9-8eb7-a0c27ca98925.PNG)

**Comment by Morris1927** [comment]
Hi, I've found that the problem is related to an old version of MonoMod.RunetimeDetour, 2.0 has been taken off thunderstore until it gets figured out. Thanks for the info

**Comment by Canadiancookie** [comment]
2.0.1 still crashes for me, with a similar message.

**Comment by Morris1927** [comment]
Hmm, did you copy + paste the `core` folder into BepInEx?

**Comment by Canadiancookie** [comment]
Looks like the issue was caused by trying to install it using [this manager.](https://thunderstore.io/package/scottbot95/RoR2ModManager/) I installed manually and it worked.

**Comment by Morris1927** [comment]
Ahh, yes that makes sense. Unfortunately managers are going to have trouble with this because of the non-standard file format. Thanks for posting your solution
